--Bài 1:
Select NAME from CITY
where POPULATION >120000 and COUNTRYCODE ='USA';
--Bài 2:
SELECT * FROM CITY
WHERE COUNTRYCODE = 'JPN';
--Bài 3:
SELECT  CITY, STATE FROM STATION;
--Bài 4:
  SELECT DISTINCT CITY FROM STATION
    WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%';
-- Bài 5:
SELECT DISTINCT CITY FROM STATION
    WHERE CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U';
-- Bài 6: 
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%';
--Bài 7: 
Select NAME from Employee
order by NAME ASC;
--Bài 8:
SELECT NAME FROM Employee
WHERE salary>2000 AND months<10
ORDER BY employee_id;
--Bài 9:
