--Bài 1:
Select NAME from CITY
where POPULATION >120000 and COUNTRYCODE ='USA';
--Bài 2:
SELECT * FROM CITY
WHERE COUNTRYCODE = 'JPN';
--Bài 3:
SELECT  CITY, STATE FROM STATION;
--Bài 4:
  SELECT DISTINCT CITY FROM STATION
    WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%';
